name: ClearMind
options:
  bundleIdPrefix: com.clearmind
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    DEAD_CODE_STRIPPING: YES

targets:
  ClearMind:
    type: application
    platform: macOS
    sources:
      - path: Craig-O-Clean
        excludes:
          - "Tests/**"
          - "Preview Content/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clearmind.controlcenter
        PRODUCT_NAME: "ClearMind Control Center"
        INFOPLIST_FILE: Craig-O-Clean/Info.plist
        CODE_SIGN_ENTITLEMENTS: Craig-O-Clean/Craig-O-Clean.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies: []
    preBuildScripts: []
    postBuildScripts: []

  ClearMindTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Craig-O-Clean/Tests/ClearMindTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clearmind.controlcenter.tests
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ClearMind Control Center.app/Contents/MacOS/ClearMind Control Center"
    dependencies:
      - target: ClearMind

  ClearMindUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: Craig-O-Clean/Tests/ClearMindUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clearmind.controlcenter.uitests
        TEST_TARGET_NAME: ClearMind
    dependencies:
      - target: ClearMind

schemes:
  ClearMind:
    build:
      targets:
        ClearMind: all
        ClearMindTests: [test]
        ClearMindUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ClearMindTests
        - ClearMindUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
